### ISSUE TITLE
How to find Album Covers and Artists Images

### ISSUE THREAD

**Issue by goxr3plus** [ajdons/Discogs4J#19]
Hi hello :) , i would like to use your library with [XR3Player ](https://github.com/goxr3plus/XR3Player)(JavaFX Media Player ) for downloading Album Covers and Artists Images :)

Can i have an example on how to do it :) ?

**Comment by ajdons** [comment]
Hi,
As stated in the readMe:
> All methods will return the response body as JSON.

You can view the JSON responses for different discogs API calls at https://www.discogs.com/developers/#page:database

From the JSON responses you can parse out links to to images hosted by discogs, which you would then have to load yourself.

For example in the [Release](https://www.discogs.com/developers/#page:database,header:database-release) response object, there is a "thumb" key for a smaller image and an "images" object which contains links to multiple sized images for the Release.
